[run]
deps=["mandelbrot"]
exec="./$<"

[check]
deps=["mandelbrot_debug"]
exec="valgrind ./$<"

[mandelbrot]
deps=["main.cc"]
exec="g++ -O3 -Wall $< -pthread -lSDL2 -o $@"

[mandelbrot_debug]
deps=["main.cc"]
exec="g++ -g -Wall $< -pthread -lSDL2 -o $@"

