[serve]
deps=["mandelbrot", "public/cache"]
exec="node server.js"

[clean-serve]
deps=["mandelbrot", "public/cache", "clean"]
exec="node server.js"

["public/cache"]
exec="mkdir --parents $@"

[clean]
exec="rm -f public/cache/*"

[display]
deps=["%.png"]
exec="display $<"

["mandelbrot.png"]
deps=["mandelbrot"]
exec="time ./$<"

[check]
deps=["mandelbrot_debug"]
exec="valgrind ./$< -W 140 -H 90 -i 10"

[mandelbrot]
deps=["main.cc", "lodepng.cpp"]
exec="g++ -DNDEBUG -O3 -Wall $+ -pthread -o $@"

[mandelbrot_debug]
deps=["main.cc", "lodepng.cpp"]
exec="g++ -g -Wall $+ -pthread -o $@"

