[display]
deps=["%.png"]
exec="display $<"

["mandelbrot.png"]
deps=["mandelbrot"]
exec="time ./$<"

[check]
deps=["mandelbrot_debug"]
exec="valgrind ./$<"

[mandelbrot]
deps=["main.cc", "lodepng.cpp"]
exec="g++ -O3 -Wall $+ -pthread -o $@"

[mandelbrot_debug]
deps=["main.cc", "lodepng.cpp"]
exec="g++ -g -Wall $+ -pthread -o $@"

