name: geotoolkit

channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - git
  - pip
  - pip:
    - numpy==1.15.4
    - scipy==1.3.1
    - git+https://github.com/geoscixyz/Toolkit.git@master
    - sphinx
    - sphinx_rtd_theme
    - sphinxcontrib-bibtex
    - nbsphinx
    - nbstripout
    - numpydoc
    - download
    - tqdm
  - matplotlib
  - ipywidgets
  - geopandas
  - scikit-image

