name: geotoolkit

channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - git
  - pip
  - numpy
  - scipy
  - pip:
    - sphinx
    - sphinx_rtd_theme
    - sphinxcontrib-bibtex<2.0.0
    - nbsphinx
    - nbstripout
    - numpydoc
    - download
    - tqdm
    - testipynb
    - pytest
  - matplotlib
  - ipywidgets
  - geopandas
  - scikit-image
