name: Testing

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  setup-build:
    name: Testing in 3.8 on ubuntu-latest
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.1.1
      with:
        environment-file: environment-dev.yml
        activate-environment: geotoolkit
        channels: conda-forge

    - name: Install package
      shell: bash
      run: |
        conda activate geotoolkit
        pip install .

    - name: Run Tests
      shell: bash
      run: |
        conda activate geotoolkit
        pytest -s -v tests

    - name: Build Doc
      # if: github.ref == 'refs/heads/main'
      shell: bash
      run: |
        conda activate geotoolkit
        cd docs
        make html
        cd ..

    - name: GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: crazy-max/ghaction-github-pages@v2.5.0
      with:
        build_dir: docs/_build/html
        jekyll: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
